# Download Data and Export NWB
This notebook downloads data from the Allen Institute's [visual coding dataset](https://allensdk.readthedocs.io/en/latest/visual_coding_neuropixels.html) and exports it using the neurodata without borders (NWB) format.
For each recording session, a single NWB file is written.

```{python}
from pathlib import Path
from datetime import timedelta
import numpy as np
from allensdk.brain_observatory.ecephys.ecephys_project_cache import EcephysProjectCache
from pynwb import NWBFile, NWBHDF5IO
from pynwb.file import Subject
from pynwb.ecephys import ElectricalSeries
from pynwb.epoch import TimeIntervals
```

## Parameters
Because the original dataset is very large (~15GB per session), only parts of the data are extracted.
The relevant parts of the data are determined by the parameters `GENOTYPES`, `SESSION_TYPES`, `BRAIN_AREAS` and `STIMULUS_TYPES`.
When `CLEAR_CACHE` is set to `True`, the downloaded files are deleted after the NWB file has been exported.
```{python}
GENOTYPES = ["wt/wt"]
SESSION_TYPES = ["brain_observatory_1.1"]
BRAIN_AREAS = ["VISpm"]
STIMULUS_TYPES = ["gabors", "flashes"]
CLEAR_CACHE = True
```

## Caching data

Data will be downloaded using the `allensdk` and stored in the directory `data/cache`.

```{python}
#| eval: false
root = Path(__file__).parent.parent.absolute()
```

```{python}
cache_dir = root/"data"/"cache"
if not cache_dir.exists():
    cache_dir.mkdir(parents=True)
```

## Get sessions

Get the table listing all recording `sessions` and filter them to only include the selected `SESSION_TYPES` and `GENOTYPES`.
```{python}
cache = EcephysProjectCache.from_warehouse(manifest=cache_dir/"manifest.json")
sessions = cache.get_session_table()
sessions = sessions[sessions.full_genotype.isin(GENOTYPES)]
sessions = sessions[sessions.session_type.isin(SESSION_TYPES)]
print(f"Selected {len(sessions)} sessions")
# sessions = sessions.iloc[:1] # for testing purposes, just do a single session
```

## Get channels

Get the table of all channels to look up electrode locations.
To save space the channels table is filtered for the `BRAIN_AREAS` of interest.
```{python}
channels = cache.get_channels()
channels = channels[channels.ecephys_structure_acronym.isin(BRAIN_AREAS)]
channels = channels[channels.ecephys_session_id.isin(sessions.index)]
```

## Download session data

Iterate the filtered sessions table and download the `session` data and `metadata`.

```{python}
#| label: ses-loop
for i_ses, session_id in enumerate(sessions.index):
    print(f"##### Sub {str(i_ses+1).zfill(2)} #####")
    session = cache.get_session_data(session_id)
    metadata = session.metadata
```


## Identify probes with channels in ROI

Check the `channels` table to find which electrodes lie in `BRAIN_AREAS` of interest and get the probe_id
```{python}
#| ref.label: ses-loop
    ses_channels = session.channels
    ses_channels = ses_channels[ses_channels.ecephys_structure_acronym.isin(BRAIN_AREAS)]
    probes = ses_channels.probe_id.unique()
```


## Find relevant time intervals

Load the stimulus table and select the epochs where the `SIMULUS_TYPES` of interest where presented.
Then, iterate the epochs and crea
```{python}
#| ref.label: ses-loop
    #| label: run-loop
    epochs = session.get_stimulus_epochs()
    epochs = epochs[epochs.stimulus_name.isin(STIMULUS_TYPES)]
    for i_epoch in range(len(epochs)):
        print(f"##### Run {i_epoch+1} #####")
        epoch = epochs.iloc[i_epoch]
        t_start = metadata["session_start_time"]+timedelta(seconds=epoch.start_time)
```


## Create new NWB file

Create a new nwb file and add information about subject.
The start time calculated by adding the start time of the `epoch` to the session's start time.
The file identifier is the original session id and the run number, separated by an underscore.
Also, we create an `ecephys_module` to store LFPs and spike times.
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop

        subject = Subject(
            subject_id = str(i_ses+1).zfill(2),
            age=f"P{int(metadata['age_in_days'])}",
            species = "Mus musculus",
            sex = metadata['sex'],
            genotype = metadata['full_genotype'],
            description = f"mouse {metadata['specimen_name']}"
            )
        nwb = NWBFile(
            session_description="Ecephys recordings for multiple Neuropixels probes",
            identifier=f"session{session_id}_run{i_epoch+1}",
            session_start_time=metadata["session_start_time"],
            )
        nwb.subject = subject
        ecephys_module = nwb.create_processing_module(
            name="ecephys", description="processed extracellular electrophysiology data"
            )
        out_fname = f"sub-{subject.subject_id}_run-{i_epoch+1}_ecephys.nwb"
        out_fpath = root/"data"/"nwb"/f"sub-{subject.subject_id}"/out_fname
        if not out_fpath.parent.exists():
            out_fpath.parent.mkdir(parents=True)
        
```

## Load LFP data

Load the recorded LFP time series and select the channels in `BRAIN_AREAS` of interest and the stime interval for the current run.
Because not all listed channels are actually in the `lfp` (probably due to signal quality), we have to check each channel before selecting the data
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        #| label: probe-loop
        for i_probe, probe_id in enumerate(probes):
            lfp = session.get_lfp(probe_id)
            probe_channels = ses_channels[ses_channels.probe_id==probe_id]
            valid_channel_ids = []
            for pc_id in probe_channels.index.to_numpy():
                if np.isin(pc_id, lfp.channel):
                    valid_channel_ids.append(pc_id)
            probe_channels = probe_channels[probe_channels.index.isin(valid_channel_ids)] 
            times = lfp.time[np.logical_and(epoch.start_time<lfp.time, lfp.time<epoch.stop_time)]
            lfp = lfp.sel(channel=probe_channels.index, time=times)
```

## Create electrode table

Before storing electrophysiological data, we have to add the elctrode that was used for recording the data.
Create 1 `device` per probe, 1 `electrode_group` per brain area (`location`) and then add the respective electrodes.
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        #| ref.label: probe-loop
            device = nwb.create_device(
                name=session.probes.loc[probe_id].description, description=f"ID {probe_id}", manufacturer="Neuropixels"
            )
            for i_loc, location in enumerate(probe_channels.ecephys_structure_acronym.unique()):
                electrode_group = nwb.create_electrode_group(
                    name=location,
                    description=f"Electrodes in {location}",
                    device=device, 
                    location=location
                )
                location_channels = probe_channels[probe_channels.ecephys_structure_acronym==location]
                for electrode_id in location_channels.index:
                    nwb.add_electrode(
                        group=electrode_group,
                        id = electrode_id,
                        location=location,
                    )
```

## Add LFP data to NWB

Now we can add the previously loaded LFP data to the NWB file.
To do this, we need a `DynamicTableRegion` that maps the `ElectricalSeries` to entries in the table stored in `nwb.electrodes`.
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        #| ref.label: probe-loop
            region=list(np.where(nwb.electrodes.id[:] == location_channels.index)[0])
            electrode_table_region = nwb.create_electrode_table_region(
                description="all electrodes", region=region,
            )

            lfp = ElectricalSeries(
                name=f"lfp{session.probes.loc[probe_id].description[-1]}",
                description="LFP data",
                data=lfp.data,
                electrodes=electrode_table_region,
                starting_time=0.0,
                rate = 1/np.diff(lfp.time)[0]
            )
            ecephys_module.add(lfp);
        
```

The [nwbpy tutorial](https://pynwb.readthedocs.io/en/stable/tutorials/domain/ecephys.html#lfp) recommends wrapping the `ElectricalSeries` inside a `LFP` class but this is counter-productive: It makes the data harder to interact with (instead of `lfp.data` you have to type `lfp.electrical_series['LFP'].data`) and we already have the `name` and `description` fields to indicate the kind of data
```{python}
            # lfp = LFP(electrical_series=lfp)
```

## Spike times
Get the table of recorded `units` and select those in `BRAIN_AREAS` of interest.
Then, get the `spike_times`, select those that belong to the selected `units` and crop them to the `epoch` interval.
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        units = session.units
        units = units[units.ecephys_structure_acronym.isin(BRAIN_AREAS)]
        spike_times = session.spike_times
        spike_times = {uid: spike_times[uid] for uid in units.index}
        for uid, spikes in spike_times.items():
            spike_times[uid] = spikes[np.logical_and(
                    spike_times[uid]>=epoch.start_time,
                    spike_times[uid]<=epoch.stop_time,
                )]
            spike_times[uid]-=spike_times[uid][0]  # start at 0
```

## Mean waveforms
Load the `mean_waveforms` of each unit, keep only the waveforms recorded at channels that are present in the nwb file's electrodes table. Then, for each unit, select the waveform with the largest peak-to-peak amplitude (i.e. from the channel closest to the unit).
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        mean_waveforms = session.mean_waveforms
        mean_waveforms = {uid: mean_waveforms[uid] for uid in units.index}
        max_waveforms = {}
        for uid, mean_waveform in mean_waveforms.items():
            mean_waveform = mean_waveform.sel(channel_id=nwb.electrodes.id[:])
            peak_to_peak = mean_waveform.data.max(axis=1) - mean_waveform.data.min(axis=1)
            max_waveforms[uid] = mean_waveform.data[np.argmax(peak_to_peak)]
```

## Add units
Add the units to the `nwb` file.

```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        for uid in units.index:
            nwb.add_unit(spike_times=spike_times[uid], waveform_mean=max_waveforms[uid], id=uid)
```

## Add running running speed

Store the running data as `TimeIntervals` with a `start_time`, `stop_time` and `velocity`.

```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        running_speed = session.running_speed
        running_speed = running_speed[running_speed.start_time>=epoch.start_time]
        running_speed = running_speed[running_speed.end_time<=epoch.stop_time]
        running_intervals = TimeIntervals(
            name="running",
            description="Intervals when the animal was running.",
        )
        running_intervals.add_column(name="velocity", description="Running velocity in cm/s.")
        for i, rs_row in running_speed.iterrows():
            running_intervals.add_row(start_time=rs_row.start_time, stop_time=rs_row.end_time, velocity=rs_row.velocity)
        nwb.add_time_intervals(running_intervals)
```

## Add stimulus info

Find out which stimulus type was presented during this run
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        stimuli = session.get_stimulus_table()
        stimuli = stimuli[stimuli.start_time>=epoch.start_time]
        stimuli = stimuli[stimuli.stop_time<=epoch.stop_time]
        stim_type = stimuli.stimulus_name.unique()
        assert len(stim_type)==1
        stim_type = stim_type[0]
```

### Full-field flashes

For flashes, we only need `start_time`, `stop_time` and `color`.
The latter indicates whether the stimulus was white (1) or black (-1).
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        if stim_type == "flashes":
            nwb.add_trial_column(name="color", description="Stimulus color (1=white, -1=black)")
            for _, stim in stimuli.iterrows():
                nwb.add_trial(start_time=stim.start_time, stop_time=stim.stop_time, color=stim.color)
```

### Gabors

For Gabor patches, we need position and orientation in x and y.
Temporal and spatial frequency, as well as size are the same for all stimuli.
```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        if stim_type == "gabors":
            nwb.add_trial_column(
                name="x_position",
                description="x coordiante of stimulus center is degrees of visual angle."
            )
            nwb.add_trial_column(
                name="y_position",
                description="y coordiante of stimulus center is degrees of visual angle."
            )
            nwb.add_trial_column(
                name="orientation",
                description="Orientation of the stimulus is degrees."
            )
            for _, stim in stimuli.iterrows():
                nwb.add_trial(
                    start_time=stim.start_time,
                    stop_time=stim.stop_time,
                    x_position=stim.x_position,
                    y_position=stim.y_position,
                    orientation=stim.orientation
                )
```

## Save results

```{python}
#| ref.label: ses-loop
    #| ref.label: run-loop
        with NWBHDF5IO(out_fpath, mode="w") as io:
            io.write(nwb)
```


